[general]
enabled = yes
webenabled = no
port = 5038
bindaddr = 127.0.0.1

[privacyapi]
secret = change-this-secret
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.255
read = system,call,log,verbose,command,agent,user,reporting,originate
write = system,call,log,verbose,command,agent,user,reporting,originate
